### ISSUE TITLE
01-日本語LLMでFlux.json SaveAnimatedWEBP

### ISSUE THREAD

**Issue by githabtane** [Zuntan03/EasyForge#2]
WARNING: [Errno 2] No such file or directory: 'D:\\EasyForge\\ComfyUI\\input\\0916_2036_00001_.webp'
!!! Exception during processing !!! 'int' object is not subscriptable
Traceback (most recent call last):
  File "D:\EasyForge\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\EasyForge\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\EasyForge\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\EasyForge\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\EasyForge\ComfyUI\nodes.py", line 1499, in save_images
    full_output_folder, filename, counter, subfolder, filename_prefix = folder_paths.get_save_image_path(filename_prefix, self.output_dir, images[0].shape[1], images[0].shape[0])
TypeError: 'int' object is not subscriptable

**Comment by Zuntan03** [comment]
ComfyUIの互換性のない変更で、すべてのSwitch文が壊れています。
修正箇所が多いので明日か明後日の修正になる見込みです。

**Comment by githabtane** [comment]
もう1台もアップデートしたところ、同じ現象が出たので
よろしくお願いします

**Comment by githabtane** [comment]
switch構文を修正したところ、正常動作しました
ありがとうございました

**Comment by Zuntan03** [comment]
ComfyUIの 10/8 版以降では Switch ノードの修正後に保存して再読み込みした際に、再度 Switch ノードが壊れるようでしたので、10/7 版でバージョン固定するようにしました。

**Comment by githabtane** [comment]
最新版では修正したものは正常に読み込める様になりました

**Comment by githabtane** [comment]
Comfyui最新版でも修正なしで動作するようです
ComfyUI-ppmをアップデートする必要がありますが
